### ISSUE TITLE
Issue 1: User can create an account

### ISSUE THREAD

**Issue by CollinHovey** [CollinHovey/final-project#1]
## ⚙️ User Can Create An Account

> ##### A user can create an account and login

## 📐 Functionality

> ##### The user will start at the login page. They can click on the create an account button to take them to the create an account page. There they fill out a username and password. They will hit sign up which will take them back to the login page if successful. They can then enter that information again and hit the login button to be taken back the homepage

## 🖼️Wireframes

> ##### 

![chrome_ZchNapHMNN](https://user-images.githubusercontent.com/102557430/181648064-34af8811-dd41-4d8b-97b3-97b8356b1a71.png)
![chrome_JmSY58TEnc](https://user-images.githubusercontent.com/102557430/181648271-df17f947-555d-442d-a3d3-8d976686c1ce.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create `schema.sql` to have the users table

### ☁️ Server Tasks

- [x] Add post request to `server/index.js` to add a new user
- [x] Add get request to `server/index.js` to check the user login is correct for login and provide auth token
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create component to render the login screen if there is no auth token
- [x] Create component to make a form in the login screen that on submission sends a get request to server to authenticate the user login, if successful, should store auth token in the local storage and render the home screen
- [x] Create component to render create new account screen when the create new account button is pressed on the login screen
- [x] Create component to make a form on create new account screen that on submission takes the fields and sends a post request to the server, if successful will return the user to the login screen

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
